---

- name: KIBANA CONFIG TASK | Ensure That Host Directories Exist [Kibana]
  file:
    path: "{{ item.host_dir }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ kibana_directories }}"
  notify: "restart_kibana_docker"

- name: KIBANA CONFIG TASK | Ensure That Config Files Exist [Kibana]
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ kibana_files }}"
  notify: "restart_kibana_docker"

- name: KIBANA DOCKER TASK | Ensure That Host Directories Exist [NGINX]
  file:
    path: "{{ item.host_dir }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: "nginx_check_config_and_reload_docker"
  with_items: "{{ kibana_nginx_directories }}"
  when: kibana_nginx is defined and kibana_nginx == true

- name: KIBANA DOCKER TASK | Ensure That Config Files Exist [NGINX]
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: "nginx_check_config_and_reload_docker"
  with_items: "{{ kibana_nginx_files }}"
  when: kibana_nginx is defined and kibana_nginx == true
